### ISSUE TITLE
Error in face recognition mode

### ISSUE THREAD

**Issue by 45clouds** [robmarkcole/deepstack-ui#51]
When I switch to face recognition mode I get the following error:

DeepstackException: Error from Deepstack request, status code: 403
Traceback:
File "/usr/local/lib/python3.8/site-packages/streamlit/script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "/app/deepstack-ui.py", line 90, in <module>
    predictions = process_image_face(pil_image, dsface)
File "/usr/local/lib/python3.8/site-packages/streamlit/caching.py", line 604, in wrapped_func
    return get_or_create_cached_value()
File "/usr/local/lib/python3.8/site-packages/streamlit/caching.py", line 588, in get_or_create_cached_value
    return_value = func(*args, **kwargs)
File "/app/deepstack-ui.py", line 57, in process_image_face
    predictions = dsface.recognize(image_bytes)
File "/usr/local/lib/python3.8/site-packages/deepstack/core.py", line 297, in recognize
    response = process_image(
File "/usr/local/lib/python3.8/site-packages/deepstack/core.py", line 130, in process_image
    raise DeepstackException(

**Comment by Na3blis** [comment]
I receive the same error when selecting face:
In my compose I have:
```
  deepstack:
    container_name: deepstack
    restart: always
    image: deepquestai/deepstack
    ports:
      - '5005:5000'
    environment:
      - VISION-DETECTION=True
    volumes:
      - /home/naeblis/deepstack:/datastore
      - /home/naeblis/deepstack/models:/modelstore/detection

  deepstack-ui:
    container_name: deepstack-ui
    restart: always
    image: robmarkcole/deepstack-ui
    ports:
      - '8501:8501'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DEEPSTACK_IP=172.17.0.1
      - DEEPSTACK_PORT=5005
      - DEEPSTACK_TIMEOUT=20
      - DEEPSTACK_UI_DEBUG_MODE=True
```
